/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package book_data_structures_and_algorithms_in_java_6ed;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
