/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package book_data_structures_and_algorithms_in_java_6ed;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
