package book_data_structures_and_algorithms_in_java_6ed.ch3_fundamental_data_structures.Reinforcement;

/**
 * Give the next five pseudorandom numbers generated by the process described on
 * page 113, with a = 12, b = 5, and n = 100, and 92 as the seed for cur.
 * 
 * next = (a ∗ cur + b) % n;
 */
public class R1 {
   public static void main(String[] args)  {
       int a = 12;
       int b = 5;
       int n = 100;

       int cur = 92;
       for (int i = 0; i < 5; i++) {
        int next = (a * cur + b) % n;
        cur = next;
        System.out.println(cur);
       }

   }
}
